language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
 before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
  - pip install -r requirements.txt
script:
  - python boston_housing_prediction/__main__.py linear_regression < testing_linear.txt
  - python boston_housing_prediction/__main__.py polynomial_regression < testing_polynomial.txt
