language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
 # command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python boston_housing_pred.py linear_regression < testing.txt
