language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python code/boston-housing-main.py linear_regression < testing.txt
